adam_epsilon: 1.0e-08
cache_dir: null
config_name: ''
data_dir: indic-glue/amrita-paraphrase-exact
dataset: amrita-paraphrase-exact
dev_lang: ta
do_predict: true
do_train: true
eval_batch_size: 32
example_type: text
fp16: false
fp16_opt_level: O1
gradient_accumulation_steps: 1
iglue_dir: indic-glue/
labels: ''
lang: ta
learning_rate: 2.0e-05
max_grad_norm: 1.0
max_seq_length: 128
mode: sequence-classification
model: ai4bharat/indic-bert
model_name_or_path: ai4bharat/indic-bert
n_gpu: 0
n_tpu_cores: 0
num_train_epochs: 3
output_dir: ../outputs/amrita-paraphrase-exact/train-ta/model-ai4bharat-indic-bert
output_mode: classification
overwrite_cache: true
seed: 2
test_lang: ta
tokenizer_name: ''
train_batch_size: 32
train_lang: ta
warmup_steps: 0
weight_decay: 0.0
